### ISSUE TITLE
REPL interface issues

### ISSUE THREAD

**Issue by cleberjamaral** [jason-lang/jason#100]
Following the tutorial [Hello World](http://jason.sourceforge.net/mini-tutorial/hello-bdi/), I think the REPL facility provided by the MAS Console is a bit confusing, and it seems there are a few issues regarding this facility (My Jason Version = "2.6-SNAPSHOT").

1) After adding a New REPL agent, the helping message shown seems to be wrong, since a semicolon at the end of the command is not allowed. For instance, "+bel;" results in "Error parsing +bel;;jason.infra.repl.print_unifier jason.asSyntax.parser.ParseException: Expected <EOF> after +bel for parameter '+bel;;jason.infra.repl.print_unifier'. It seems a "." (dot) or nothing at the end are the right ways to end a REPL command.
2) It is not clear why there are two "New agent" buttons and if I close the REPL interface I did not find a way to open it again. Maybe, it would be better to have only the "New agent" button to add an agent and replace the "New  REPL agent" button by "open REPL interface", so we can open a REPL interface for any existing agent.
3) When I add an agent from the New REPL agent, the MAS Console does not add a tab to it (i.e., I cannot debug it from the opened MAS Console).
4) It seems the ".mi" command is a bit problematic in some platforms (https://stackoverflow.com/questions/18004150/desktop-api-is-not-supported-on-the-current-platform).

**Comment by jomifred** [comment]
Thanks Cleber for the feedback!

item 1: the help messages are fixed.
item 2: it looks like a good proposal, I am adding it in the ToDo list
item 3: to be fixed

**Comment by jomifred** [comment]
done and committed in develop  branch
