### ISSUE TITLE
Trigonometry functions not loaded by default

### ISSUE THREAD

**Issue by nmontesg** [jason-lang/jason#102]
While using a Jason agent as a standalone class, I found out that the trigonometry arithmetic functions (`math.sin, cos, tan, asin, acos, atan`) are not loaded into the agent by default. Although I didn't do an exhaustive check, all other arithmetic functions seem to be loaded by default. I could solve this by hardcoding (`addFunction(jason.functions.atan.class)`), but I guess that the expectation is for all functions in jason.functions to be loaded by default when the agent class is initialized.

Thank you,

Nieves

**Comment by jomifred** [comment]
Thanks Nieves for reporting this problem. It is fixed in develop branch and SNAPSHOT build. Next release will include this fix.
