### ISSUE TITLE
Javadoc not accessible

### ISSUE THREAD

**Issue by vcharpenay** [jason-lang/jason#104]
Parts of the Jason documentation that are hosted on Sourceforge aren't accessible anymore. That's e.g. the case of a page I've often been visiting :

http://jason.sourceforge.net/api/jason/stdlib/package-summary.html#package.description

For now, I guess I'll have to compile Javadoc from the code base. Is it hosted elsewhere on the Web?

**Comment by jomifred** [comment]
Thanks for reporting this problem. We are facing some problem in the source forge host. 

The API is now available at [http://jason-lang.github.io/jason/api/](http://jason-lang.github.io/jason/api/)

The internal actions link is [http://jason-lang.github.io/jason/api/jason/stdlib/package-summary.html](http://jason-lang.github.io/jason/api/jason/stdlib/package-summary.html)
