### ISSUE TITLE
Add agent runtime from code

### ISSUE THREAD

**Issue by Breinich** [jason-lang/jason#105]
I would like to ask, is there a way to add a new agent instance runtime from code, like the way you can do from the MAS window?

As I've browsed the code maybe if I could get to the Mas2jProject instance then I could call the addAgent function, am I on the right way?

Thank you for your help!

**Comment by jomifred** [comment]
hi Vencel,

you can use the .create_agent internal action. See the doc at

	https://jason-lang.github.io/api/jason/stdlib/package-summary.html

HTH,

Jomi

**Comment by Breinich** [comment]
Thank you very much Jomi!

**Comment by Breinich** [comment]
This is what I really thought about, my mistake that I haven't read the FAQ before asking the question:

https://jason-lang.github.io/doc/faq#is-it-possible-to-addremove-an-agent-tofrom-a-running-mas
