### ISSUE TITLE
.wait makes agents halt when passing a formula

### ISSUE THREAD

**Issue by igorcadelima** [jason-lang/jason#12]
I've been facing some difficulties trying to get `.wait` to work as described in the [documentation](http://jason.sourceforge.net/api/jason/stdlib/wait.html).

Why does the agent never print the message in the code below?

```
day(saturday).
!start.
+!start 
  <- 
  .wait(day(saturday));
  .print("hello world.").
```

Thanks in advance.

**Comment by jomifred** [comment]
Thanks Igor for reporting this. It is clearly a bug. Fixed in Jason GitHub repository.

**Comment by igorcadelima** [comment]
I just downloaded the code from repo and I can confirm the bug's gone. Thanks heaps!
