### ISSUE TITLE
else if keyword

### ISSUE THREAD

**Issue by copycat-killer** [jason-lang/jason#13]
I know it might be considered syntactic sugar by some, but for the sake of completeness, there should be an `else if` or `elseif` keyword, as implemented by every language.

EDIT:

A little OT. In a plan, I happened to forgot setting a variable which is used in a `.wait` logical formula.
I had an error like this:

```java
[alice] Error in internal action '.wait([...])' (/path/to/alice.asl): null
```
I struggled a bit to figure out what that `null` was referring to, since I also had some other variables in the formula. So, it is preferable that the `null` error message would also include which variables are actually null.

**Comment by jomifred** [comment]
for the elseif, certainly a good ToDo!

for the .wait error, could you send us the complete parameter used for .wait? thanks

**Comment by igorcadelima** [comment]
Please, consider using `elif` like in Python. Fewer characters to write :)

**Comment by copycat-killer** [comment]
@jomifred 

> for the .wait error, could you send us the complete parameter used for .wait? thanks

You can use whatever unsetted variable. For instance:

```
.wait(N * 1000);
```

Of course in this case it's immediate to understand that N is causing the issue, but in a general case where one could use more complex logical formulas, it's not.

**Comment by jomifred** [comment]
done in jason 2.2
