### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by lcpz** [jason-lang/jason#15]
Hi, the first 5 links listed in "Technical documents" [here](https://github.com/jason-lang/jason/tree/master/doc) are not working.

Maybe these files were untracked by Git.

**Comment by jomifred** [comment]
Hi Luca, thanks for your remark. 

The readme.adoc file is used to build the readme.html in the distribution package (jason-xxx.zip), where the links are (locally) fixed. It wasn't supposed to be browsed in the github.

Anyway, the avoid this problem, I removed some broken links from the github view.

thanks.

Jomi
