### ISSUE TITLE
Question about variable substitution

### ISSUE THREAD

**Issue by igorcadelima** [jason-lang/jason#17]
Hello!

How could I rewrite the code below so that I could unify `V` with `any_literal1(10,an_atom) & any_literal2("string")`?
```
test(any_literal1(A,an_atom) & any_literal2(B)).
!start.
+!start
   <-
   A = 10;
   B = "string";
   ?test(V);
   .print(V).
```
Cheers,
Igor.

**Comment by rbordini** [comment]
Hi Igor,

Have a look at Unification in a Prolog book, it works the same. If you 
need to convert an atom to string, see "term2string" in "stdlib" at:
http://jason.sourceforge.net/api/

Best,

Rafael

**Comment by jomifred** [comment]
Hi Igor, 

the value of V, as printed, does not include the vars A and B anymore, since their are anonymized to not clash with local variables. It is a desired effect in general case, although it is not in yours.

I am not sure whether it is suitable for you, but you can add A and B in the test:

test(A,B,any_literal1(A,an_atom) & any_literal2(B)).
```
!start.
+!start <-  A = 10;   B = "string";
   ?test(A,B,V);
   .print(V).
```

**Comment by igorcadelima** [comment]
Hi Jomi.

Thanks for the reply! The workaround you proposed isn't actually suitable for me atm. I'd like to have the term of `test/1` to be any logical formula with any number of variables. Just like `A` and `B` from the code above, the values of these variables would be always known at the beginning of `start`.

Isn't there a way to apply a substitution to `V` using the context as unifier then? (not sure if I used correct technical terms here)

**Comment by jomifred** [comment]
if you can “store" the logical expression as a string, you can use the .term2string proposed by Rafael:

test("any_literal1(A,an_atom) & any_literal2(B)").
!start.
+!start <- A = 10; B = "string";
   ?test(V);
   .term2string(T,V);
   .print(T);
   .

**Comment by jomifred** [comment]
With a bit of meta-programming:

test(any_literal1(A,an_atom) & any_literal2(B)).
!start.
+!start <- A = 10; B = "string";
   ?test(V);
   .relevant_rules(test(_),LR); // gets all rules 
   for (.member(R,LR)) {
       .print(R);
   }
   .


> On 31 de out de 2017, at 15:29, Igor Conrado Alves de Lima <notifications@github.com> wrote:
> 
> Hi Jomi.
> 
> Thanks for the reply! The workaround you proposed isn't actually suitable for me atm. I'd like to have the term of test/1 to be any logical formula with any number of variables. Just like A and B from the code above, the values of these variables would be always known at the beginning of start.
> 
> Isn't there a way to apply a substitution to V using the context as unifier then? (not sure if I used correct technical terms here)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by igorcadelima** [comment]
Thank you both for your help! 

The first option worked for me and is definitely a solution for the issue described. However, it doesn't really work with the following code:
```
test("any_literal1(A,an_atom) & any_literal2(B)").
!start.
+!start
  <-
  Plan = {
  	+!plan
      :
      A = 10 &
      B = "string"
      <- 
      ?test(V);
      .term2string(T,V);
      .print(T)
  };
  .rename_apart(Plan,RenamedPlan);
  .add_plan(RenamedPlan);
  !plan.
```
The output produced is `(any_literal1(A,an_atom) & any_literal2(B))`. For this case, the use of `.rename_apart` is actually dispensable, but in my scenario its use is really important.

Anything I can do in this case?

Cheers.

**Comment by jomifred** [comment]
I guess you can look at the implementation of the internal action .rename_apart and create your own version with a third parameter for variables to ignore in the rename…. 



> On 31 de out de 2017, at 18:13, Igor Conrado Alves de Lima <notifications@github.com> wrote:
> 
> Thank you both for your help!
> 
> The first option worked for me and is definitely a solution for the issue described. However, it doesn't really work with the following code:
> 
> test("any_literal1(A,an_atom) & any_literal2(B)").
> !start.
> +!start
>   <-
>   Plan = {
>   	+!plan
>       :
>       A = 10 &
>       B = "string"
>       <- 
>       ?test(V);
>       .term2string(T,V);
>       .print(T)
>   };
>   .rename_apart(Plan,RenamedPlan);
>   .add_plan(RenamedPlan);
>   !plan.
> 
> The output produced is (any_literal1(A,an_atom) & any_literal2(B)). For this case, the use of .rename_apart is actually dispensable, but in my scenario its use is really important.
> 
> Anything I can do in this case?
> 
> Cheers.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by igorcadelima** [comment]
Alright. I'll have look at it. Thanks!
