### ISSUE TITLE
Print out double quotes using .print

### ISSUE THREAD

**Issue by igorcadelima** [jason-lang/jason#18]
Hi,

I've been trying to print double quotes by passing a string with `\"` to `.print` but the output actually shows the backslash as well.

Example:
`+!start : true <- .print("\"hello\" world.").`

Outputs:
> [sample_agent] \\"hello\\" world.

Is there a way, using `.print`, to print out _"hello" world_?

Cheers.

**Comment by jomifred** [comment]
this bug is now fixed. thanks for reporting.
