### ISSUE TITLE
Synchronous mode creates kqml_received events on receiving "achieve" speech acts

### ISSUE THREAD

**Issue by cartisan** [jason-lang/jason#20]
Dear jomifred et al,

This is maybe just a clarification request: I switched to a synchronous execution of agent's reasoning cycles by using `executionControl: jason.control.ExecutionControl` in my mas2j (as per p.96 of the Jason book). What happens is that in the synchronous mode, during reception of speech acts of the illocutionary force `achieve`, an internal event called `kqml_received` is generated (which does not happen in asynchronous mode). This happens due to `TransitionSystem` lines 353 to 372 (in current master), where a certain optimization procedure is excluded in synchronous mode.

This additional event is somewhat disruptive for my purposes, so I disabled this behavior by removing `!setts.isSync()` on line 353. My simulation works as expected and I experienced no other problems. Hence my question: What is the rationale for adding the `kqml_received` event in synchronous mode? Do I risk something by removing it?

(A side effect of this situation is that the system changes its behavior during debugging, because the "-debug" mode basically switches to `executionControl: jason.control.ExecutionControlGUI`. By that it introduces internal `kqml_received` events which are not present in the normal execution process. I think this might be dangerous in terms of debugging methodology?)

**Comment by jomifred** [comment]
Hi,

for sure to remove the !…isSync() test will not change anything on your case. The only reason (I remember :-) is that we preferred to run debug mode without the optimisation (that bypasses the kqml_receive events), since the “normal” situation is to produce such events so that the user can change the semantics of kqml performatives.

best,

Jomi

**Comment by rbordini** [comment]
Hi Leonid,

That's a very interesting question. Like Jomi I think that's the only 
reason. Note that debugging always changes the execution of a Jason 
system. This is a big problem indeed, but one that is hard in general 
(debugging a distributed system is not easy). Just by changing from a 
normal asynchronous execution to a synchronous one which we need for the 
Mind Inspector to work already makes bugs that exist in the original 
system not to happen anymore. If you have not changed the semantics of 
the performatives, it's safe for you to skip the events, but in general 
they are needed.

Cheers,

Rafael

**Comment by cartisan** [comment]
Dear Rafael, der Jomi,

thanks a lot for the clarification, that helps me to feel more comfortable about my decision. I will close the issue now. :)

Also, in my last post, I forgot to mention how much I appreciate the work you are doing here! I use and extend Jason for my dissertation project and the framework has been a great foundation for my work. Thank you very much!

Best,
Leonid
