### ISSUE TITLE
NoSuchMethod Error

### ISSUE THREAD

**Issue by fahidRM** [jason-lang/jason#22]
Hi, 
I recently implemented an Environment that extends `jason.environment.Environment`. It's code is similar to that of `jason.environment.TimeSteppedEnvironment` with a few changes. Anyway, when running the project using `Jason 2.3 (source: Sourceforge)`, I get the error shown below;

``` 
Exception in thread "demo" java.lang.NoSuchMethodError: 
                     jason.environment.EnvironmentInfraTier.getRunTimeServices()Ljason/runtime/RuntimeServices; at...

```

It works perfectly well using `jason 2.2` and I checked the source for `jason.environment.Environment` on this repository and the method is both present and public.

I am uncertain if the issue is with the build on Sourceforge but the Environment seems to have the same methods in `version 2.3`. I look forward to your response.

**Comment by jomifred** [comment]
Hi, 
the class RuntimeServicesInfraTier was renamed to RuntimeServices in 2.3, could you verify if you are using this class?
Thanks
Jomi

**Comment by fahidRM** [comment]
Hi, 
I am using the class RuntimeServiceInfraTier.
This is the line of code that calls it 
`setNbAgs(getEnvironmentInfraTier().getRuntimeServices().getAgentsNames().size()`

**Comment by jomifred** [comment]
So I guess you only need to clean and rebuild your project.
