### ISSUE TITLE
getAnnot

### ISSUE THREAD

**Issue by amdia** [jason-lang/jason#33]
Hello,
the function getAnnot has the same kind of behavior than hasSubsetAnnot had.
example :
b(a)[annot2,annot3,annot1(x),source(self)]
if I do belief.getAnnot("annot1"), it returns false because annot1 is first in the alphabetical order but because it has a greater arity, it is after annot2 and annot3 in the order of the annotations.

**Comment by jomifred** [comment]
Hi, 

in this case, the literal does not have the annotation “annot1”, it has “annot1(x)”. 




> On 6 May 2019, at 15:26, amdia <notifications@github.com> wrote:
> 
> Hello,
> the function getAnnot has the same kind of behavior than hasSubsetAnnot had.
> example :
> b(a)[annot2,annot3,annot1(x),source(self)]
> if I do belief.getAnnot("annot1"), it returns false because annot1 is first in the alphabetical order but because it has a greater arity, it is after annot2 and annot3 in the order of the annotations.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by amdia** [comment]
Does not the function getAnnot take only the functor as argument ? I tried with  belief.getAnnot("annot1(_)") but it doesn't work neither.

**Comment by jomifred** [comment]
unification is not considered, so vars should be equal.

the arg should be a term, as in

	…getAnnot(ASSyntax.createStructure(“annot1”, new Atom(“x”)))…

another option is to iterator over all annots and test their .toString() presentation.


> On 6 May 2019, at 15:37, amdia <notifications@github.com> wrote:
> 
> Does not the function getAnnot take only the functor as argument ? I tried with belief.getAnnot("annot1(_)") but it doesn't work neither.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by amdia** [comment]
I'm not sure to have understood what you meant, maybe I wasn't clear about what I wanted to do. I wanted to get the value x of annot1. I managed to do it with :
Literal l = (Literal) inBB.getAnnots("annot1").get(0);
int time = (int) ((NumberTermImpl)l.getTerm(0)).solve();

**Comment by jomifred** [comment]
You find a better solution than the one I proposed :-)

> On 7 May 2019, at 05:03, amdia <notifications@github.com> wrote:
> 
> I'm not sure to have understood what you meant, maybe I wasn't clear about what I wanted to do. I wanted to get the value x of annot1. I managed to do it with :
> Literal l = (Literal) inBB.getAnnots("annot1").get(0);
> int time = (int) ((NumberTermImpl)l.getTerm(0)).solve();
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by jomifred** [comment]
Anyway, I changed the order of annotations so that your original getAnnot("annot1") works.

**Comment by amdia** [comment]
I have not tested it yet but thank you :)
