### ISSUE TITLE
.substring as startswith and endswith

### ISSUE THREAD

**Issue by cleberjamaral** [jason-lang/jason#43]
Hi,
I am trying to use [.substring](http://jason.sourceforge.net/api/jason/stdlib/substring.html) as **startswith** and **endswith** of java, adding the third argument for unifying the position in the string. Trying the following code I had in both tests a **contains** behaviour instead of startswith and endswith.

```
+!test_starts_with 
    <-
    // Test startswith
    for (.member(S,["test_ss","somess_test_abc","test_j_ss"])) {
      if (.substring("test",S,0)) {
        .print(S);
      }
    }
    // Test endswith
    for (.member(S,["test_ee","someee_test_abc","test_j_ee"])) {
      P =  .length(S) - .length("ee");
      if (.substring("ee",S,P)) {
        .print(S);
      }
    }
.
```
Here the output I had. Notice, in both cases it was expected to do not print the second element.

```
[test_sample_agent] test_ss
[test_sample_agent] somess_test_abc
[test_sample_agent] test_j_ss
[test_sample_agent] test_ee
[test_sample_agent] someee_test_abc
[test_sample_agent] test_j_ee
```
I am doing something wrong?

**Comment by jomifred** [comment]
Thanks Cleber for reporting this bug. It is fixed in branch develop.
