### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by leonardocbalbino** [jason-lang/jason#54]
I am a student and I am studying SMA with Jason, I wanted to create an environment with a single agent instantiated several times circulating randomly in an environment

**Comment by cleberjamaral** [comment]
If you like to learn by examples I think you can try Jason examples (the ones that are available in [examples](https://github.com/jason-lang/jason/tree/master/examples) folder). There is an introduction to some of these examples in [Jason documentation](http://jason.sourceforge.net/wp/examples/). I like very much [Gold Miners example](https://github.com/jason-lang/jason/tree/master/examples/gold-miners) which seems to be close of what you are looking for. You can try to just install Jason and run the examples. It is supposed to work straightforward if you follow Jason's installation instructions.

Another interesting example you can try after a visit on Jason examples, is the [Gold Miners but using JaCaMo](http://jacamo.sourceforge.net/tutorial/gold-miners/) approach. In this case the environment is designed in CArtAgO and the organization apparatus (Moise) is used.

**Comment by leonardocbalbino** [comment]
Ok, thank you

**Comment by leonardocbalbino** [comment]
Fala português? 
Obrigado pela ajuda, os materiais ajudarão muito.
