### ISSUE TITLE
Random: support setting a seed

### ISSUE THREAD

**Issue by TimKam** [jason-lang/jason#59]
Now that @cleberjamaral is implementing testing capabilities as part of Jason core, I am wondering if it makes sense to change the implementation of ``math.random`` to allow setting a [random seed](https://en.wikipedia.org/wiki/Random_seed).
This would be very useful to test stochastic algorithms.
A straight-forward change would be to use ``java.util.Random.nextDouble()`` or similar instead of ``Math.random()``, and to allow specifying the seed as an optional argument.

What do you think? I can add a pull request.

**Comment by jomifred** [comment]
Hi Timotheus, you are absolutely right regarding the necessity of seeds. 

Currently, we have both, an internal action and a function to produce random numbers (jason/stdlib/random.java and jason/functions/Random.java, respectively). Maybe a new internal action math.set_ramdom_seed is enough...

Of course, a PR is welcome.
