### ISSUE TITLE
Student : Query regarding demo : Contract Net Protocol

### ISSUE THREAD

**Issue by Aviral190694** [jason-lang/jason#8]
Hi, 
We few student at Delhi University are using jason-lang to write few programs under our course. I want to ask few queries. 
What should be the right way to take input if we want to give the contract amount ourself. Should we create a JAVA file and then take input from that or can we take the input from JASON only?

Thank you.

**Comment by rbordini** [comment]
Hi,
If you are using just Jason, in the "demos" folder there is an example 
of how to add a graphical interface to get input from user. If you are 
using JaCaMo, the house-building example has artifact for a graphical 
interface, you can use it as an example and just add the Java components 
for user input.
Best,
Rafael

**Comment by Aviral190694** [comment]
Thank you so much sir for the quick reply. We are only using Jason. I will surely let you know if I find some error. 
I hope I am not troubling you.
Thanks
