### ISSUE TITLE
Maven/Gradle Release for Jason 2.6

### ISSUE THREAD

**Issue by MikeVezina** [jason-lang/jason#84]
Hello! I hope you are all doing well and staying safe! 

Right now I am using a locally built version of Jason 2.6 for my agents and I was just wondering if there was any way you could publish version 2.6 on Maven? No pressure at all, but it definitely would be greatly appreciated!

Thank you in advance for your help!

Michael

**Comment by cleberjamaral** [comment]
Hi Michael,

Thanks for this enquire. The following setup can be used on gradle:

repositories {
  maven { url "https://raw.github.com/jacamo-lang/mvn-repo/master" }
}
dependencies {
  compile group: 'org.jason' , name: 'jason' , version: '2.6-SNAPSHOT',
changing: true, transitive: false
}

For maven, I guess the following setup works.

<repository>
<id>jacamo-repo</id>
<name>jacamo repo</name>
<url>https://raw.github.com/jacamo-lang/mvn-repo/master</url>
</repository>

<dependency>
    <groupId>org.jason</groupId>
    <artifactId>jason</artifactId>
    <version>2.6-SNAPSHOT</version>
</dependency>

HTH

--
Cleber Jorge Amaral

**Comment by MikeVezina** [comment]
Awesome! This worked wonderfully. Thank you so much Cleber!
