### ISSUE TITLE
Make Jason available via some Maven Repository

### ISSUE THREAD

**Issue by gciatto** [jason-lang/jason#90]
It is not clear if Jason is available via Maven or not.

I'm aware that http://jacamo.sourceforge.net/maven2/ is a Maven repository where Jason can be attained from using the `org.jason-lang:jason:VERSION` id, but it is not clear to me whether this is intented for public availability or it is unofficial.
In the second case, it would be nice to have an official Maven repository for importing Jason as a dependency.
In the first case, can we assume the repository always contains the last version of Jason?

**Comment by cleberjamaral** [comment]
Sourceforge repo is for public availability. However, due to instabilities Jason's last versions are going to another repo, on [github](https://github.com/jacamo-lang/mvn-repo/tree/master/org/jason/jason).

To add this repository to your gradle files, please add this dependency:
```
repositories {
    maven { url "https://raw.github.com/jacamo-lang/mvn-repo/master" }
}
```

**Comment by gciatto-unibo** [comment]
I see. This is not actually a real Maven repository... is that a definitive solution?

May I suggest to use Maven Central instead?

**Comment by jomifred** [comment]
Thanks @gciatto-unibo  for the questions.

I agree that Maven Central is ideal. We used to upload Jason there... and still intent to place stable releases there.

But I failed to automatize a task for that and ended up using a git hub project simply because it is faster/simpler to update the jars.

**Comment by gciatto-unibo** [comment]
What's the issue there? Maybe I can help

**Comment by jomifred** [comment]
I didn't succeed to automatize (by gradle) the publishing in Maven Central. The last time I tried, I have to access a web site and do a lot of click there... something I do not like.

**Comment by gciatto-unibo** [comment]
Asking for permission on OSSRH is a once-in-life activity. I now it's boring but it's worth the time :)
Concerning the automation, maybe I can provide some tutorial I you want.
I'm glad to help :)

**Comment by jomifred** [comment]
Thanks Giovanni for supporting this task. Jason is finally on maven central:  https://central.sonatype.com/artifact/io.github.jason-lang/jason-interpreter
